services:
  - type: worker
    name: celery-worker
    region: ohio
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery --app tasks worker --loglevel info --concurrency 4"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: celery-redis
          type: redis
          property: connectionString

  - type: redis
    name: celery-redis
    region: ohio
    plan: starter  # Redis with persistence enabled
    maxmemoryPolicy: noeviction  # Recommended for Celery
    ipAllowList: []  # Allow internal access only
